_target_: src.models.time_module.TSModule
feature_name: ${datamodule.feature_name}
target_name: ${datamodule.target_name}
id_name: ${datamodule.id_name}
save_dir: ${paths.output_dir}/datamodule

optimizer:
  _target_: torch.optim.RAdam
  _partial_: true
  # lr: 0.001
  lr: 1e-3
  weight_decay: 0.002

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 50

net:
  _target_: src.models.components.transformer_model.TransformerModel
  input_size : 0
  output_size: 0
  dropout: 0
  d_model: 64
  nhead: 2
  dim_feedforward: 64
  mlp_dim: 64
  nlayers: 3
