# @package _global_

defaults:
  - _self_
  - datamodule: ts_datamodule.yaml # choose datamodule with `test_dataloader()` for evaluation
  - model: transformer.yaml
  - logger: null
  - trainer: default.yaml
  - paths: default.yaml
  - extras: default.yaml
  - hydra: default.yaml

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: ???
