# @package _global_

defaults:
  - _self_
  # - datamodule: ts_datamodule.yaml # choose datamodule with `test_dataloader()` for evaluation
  # - model: transformer.yaml
  - logger: null
  # - trainer: default.yaml
  - paths: default.yaml
  - extras: default.yaml
  - hydra: default.yaml

task_name: "synthetic"

tags: ["dev"]

save_name: "dataset_synthetic"
operations:
    - parquet
    - create_split

properties:
  nb_simulation: 15000 # number of samples created
  n_points: 500 # number of time steps in the time series
  n_support: 100 # length of the support for the feature used to classify the sample
  n_feature: 1 # number of features
  f_base: # range of frequency used for the base sine wave
    - 2
    - 5
  f_sin: # range of frequency used for the support sine wave
    - 10
    - 50
  quantile_class: # quantile used to define the class of the sample. They can be more than 2 classes
    - 0.5
    - 1
  dataset_split: [0.8, 0.2]
  target_snr: # 1. True: add noise to signal, and indicate the target SNR_dB, which is (P_signal_dB-P_noise_dB); 2. False: without noise
    - True
    - 20